import { useCallback } from 'react';
import { useTenantApi } from '@/lib/api/tenant';
import type { CreateGoalContributionInput, CreateGoalInput, FinanceGoal, FinanceGoalContribution, FinanceGoalProgress, FinanceGoalSummary, UpdateGoalInput } from './types';

interface ApiGoal { id:string; organization_id:string; name:string; target_amount_minor:number; currency:'IDR'; start_date:string; target_date:string; status:FinanceGoal['status']; metadata:Record<string,unknown>; created_at:string; updated_at:string; }
interface ApiProgress { goal_id:string; name:string; target_amount_minor:number; current_amount_minor:number; remaining_amount_minor:number; progress_percentage:number|null; start_date:string; target_date:string; status:FinanceGoalProgress['status']; configured_status:FinanceGoalProgress['configuredStatus']; currency:'IDR'; contribution_count:number; days_remaining:number; }
interface ApiContribution { id:string; organization_id:string; goal_id:string; amount_minor:number; currency:'IDR'; contributed_at:string; status:FinanceGoalContribution['status']; note:string; reference:string; idempotency_key:string; metadata:Record<string,unknown>; created_at:string; updated_at:string; }

const mapGoal=(x:ApiGoal):FinanceGoal=>({id:x.id,organizationId:x.organization_id,name:x.name,targetAmountMinor:x.target_amount_minor,currency:x.currency,startDate:x.start_date,targetDate:x.target_date,status:x.status,metadata:x.metadata,createdAt:x.created_at,updatedAt:x.updated_at});
const mapProgress=(x:ApiProgress):FinanceGoalProgress=>({goalId:x.goal_id,name:x.name,targetAmountMinor:x.target_amount_minor,currentAmountMinor:x.current_amount_minor,remainingAmountMinor:x.remaining_amount_minor,progressPercentage:x.progress_percentage,startDate:x.start_date,targetDate:x.target_date,status:x.status,configuredStatus:x.configured_status,currency:x.currency,contributionCount:x.contribution_count,daysRemaining:x.days_remaining});
const mapContribution=(x:ApiContribution):FinanceGoalContribution=>({id:x.id,organizationId:x.organization_id,goalId:x.goal_id,amountMinor:x.amount_minor,currency:x.currency,contributedAt:x.contributed_at,status:x.status,note:x.note,reference:x.reference,idempotencyKey:x.idempotency_key,metadata:x.metadata,createdAt:x.created_at,updatedAt:x.updated_at});

export function useGoalApi(){
 const tenantApi=useTenantApi();
 const listGoals=useCallback(async(status?:string)=>{const q=status?'?status='+encodeURIComponent(status):'';const r=await tenantApi.request<ApiGoal[]>('/finance/goals/'+q);return r.data.map(mapGoal);},[tenantApi]);
 const getGoal=useCallback(async(id:string)=>{const r=await tenantApi.request<{goal:ApiGoal;progress:ApiProgress}>('/finance/goals/'+encodeURIComponent(id)+'/');return {goal:mapGoal(r.data.goal),progress:mapProgress(r.data.progress)};},[tenantApi]);
 const createGoal=useCallback(async(i:CreateGoalInput)=>{const r=await tenantApi.request<ApiGoal>('/finance/goals/',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:i.name,target_amount_minor:i.targetAmountMinor,currency:i.currency??'IDR',start_date:i.startDate,target_date:i.targetDate,metadata:i.metadata??{}})});return mapGoal(r.data);},[tenantApi]);
 const updateGoal=useCallback(async(id:string,i:UpdateGoalInput)=>{const r=await tenantApi.request<ApiGoal>('/finance/goals/'+encodeURIComponent(id)+'/',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...i.name!==undefined&&{name:i.name},...i.targetAmountMinor!==undefined&&{target_amount_minor:i.targetAmountMinor},...i.currency!==undefined&&{currency:i.currency},...i.startDate!==undefined&&{start_date:i.startDate},...i.targetDate!==undefined&&{target_date:i.targetDate},...i.status!==undefined&&{status:i.status},...i.metadata!==undefined&&{metadata:i.metadata}})});return mapGoal(r.data);},[tenantApi]);
 const archiveGoal=useCallback(async(id:string)=>{const r=await tenantApi.request<ApiGoal>('/finance/goals/'+encodeURIComponent(id)+'/',{method:'DELETE'});return mapGoal(r.data);},[tenantApi]);
 const getSummary=useCallback(async(today?:string)=>{const r=await tenantApi.request<any>('/finance/goals/summary/'+(today?'?today='+encodeURIComponent(today):''));return {currency:r.data.currency,goalCount:r.data.goal_count,activeCount:r.data.active_count,completedCount:r.data.completed_count,overdueCount:r.data.overdue_count,totalTargetAmountMinor:r.data.total_target_amount_minor,totalCurrentAmountMinor:r.data.total_current_amount_minor,goals:r.data.goals.map(mapProgress)} satisfies FinanceGoalSummary;},[tenantApi]);
 const listContributions=useCallback(async(goalId:string)=>{const r=await tenantApi.request<ApiContribution[]>('/finance/goals/'+encodeURIComponent(goalId)+'/contributions/');return r.data.map(mapContribution);},[tenantApi]);
 const createContribution=useCallback(async(goalId:string,i:CreateGoalContributionInput)=>{const r=await tenantApi.request<ApiContribution>('/finance/goals/'+encodeURIComponent(goalId)+'/contributions/',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({amount_minor:i.amountMinor,currency:i.currency??'IDR',contributed_at:i.contributedAt,note:i.note??'',reference:i.reference??'',idempotency_key:i.idempotencyKey??'',metadata:i.metadata??{}})});return mapContribution(r.data);},[tenantApi]);
 const voidContribution=useCallback(async(goalId:string,id:string)=>{const r=await tenantApi.request<ApiContribution>('/finance/goals/'+encodeURIComponent(goalId)+'/contributions/'+encodeURIComponent(id)+'/',{method:'DELETE'});return mapContribution(r.data);},[tenantApi]);
 return {...tenantApi,listGoals,getGoal,createGoal,updateGoal,archiveGoal,getSummary,listContributions,createContribution,voidContribution};
}
