# Generated by Django 5.2.17 on 2026-09-19

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("organizations", "0001_initial")]
    operations = [
        migrations.CreateModel(
            name="FinanceTransaction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("direction", models.CharField(choices=[("income", "Income"), ("expense", "Expense")], db_index=True, max_length=8)),
                ("amount_minor", models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ("currency", models.CharField(default="IDR", max_length=3)),
                ("category", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("status", models.CharField(choices=[("posted", "Posted"), ("void", "Void")], db_index=True, default="posted", max_length=8)),
                ("reference", models.CharField(blank=True, max_length=150)),
                ("idempotency_key", models.CharField(blank=True, max_length=100)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="finance_transactions", to="organizations.organization")),
            ],
            options={
                "db_table": "finance_transactions",
                "ordering": ("-occurred_at", "-created_at"),
                "indexes": [
                    models.Index(fields=["organization", "occurred_at"], name="finance_tx_org_occurred_idx"),
                    models.Index(fields=["organization", "direction", "status"], name="finance_tx_org_flow_idx"),
                ],
                "constraints": [models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)) & ~models.Q(("idempotency_key", "")), fields=("organization", "idempotency_key"), name="finance_tx_org_idempotency_unique")],
            },
        ),
    ]
