# Generated by Django 5.2.17 on 2026-09-06 00:43

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("key", models.CharField(db_index=True, max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message="Product keys must be lowercase kebab-case identifiers.", regex="^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$")])),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("active", "Active"), ("inactive", "Inactive"), ("deprecated", "Deprecated")], db_index=True, default="active", max_length=16)),
                ("product_type", models.CharField(choices=[("internal", "Internal"), ("external", "External"), ("partner", "Partner"), ("platform", "Platform")], db_index=True, default="platform", max_length=16)),
                ("version", models.CharField(blank=True, max_length=32)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={"db_table": "products", "ordering": ("name", "created_at"), "indexes": [models.Index(fields=["status", "product_type"], name="product_status_type_idx")]},
        ),
    ]
