# Generated by Django 5.2.17 on 2026-09-05 23:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(name="Permission", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ("created_at", models.DateTimeField(auto_now_add=True)),
            ("updated_at", models.DateTimeField(auto_now=True)),
            ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
            ("code", models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message="Permission codes must be lowercase dot-separated identifiers.", regex="^[a-z][a-z0-9]*(\\.[a-z][a-z0-9]*)+$")])),
            ("name", models.CharField(max_length=150)),
            ("description", models.TextField(blank=True)),
            ("category", models.CharField(blank=True, max_length=64)),
            ("is_system", models.BooleanField(default=False)),
        ], options={"db_table": "access_permissions", "ordering": ("code",), "indexes": [models.Index(fields=["category"], name="access_perm_category_idx")]}),
        migrations.CreateModel(name="Role", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ("created_at", models.DateTimeField(auto_now_add=True)),
            ("updated_at", models.DateTimeField(auto_now=True)),
            ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
            ("name", models.CharField(max_length=100)),
            ("slug", models.SlugField(max_length=100)),
            ("description", models.TextField(blank=True)),
            ("is_system", models.BooleanField(default=False)),
            ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="roles", to="organizations.organization")),
        ], options={"db_table": "access_roles"}),
        migrations.CreateModel(name="RolePermission", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ("created_at", models.DateTimeField(auto_now_add=True)),
            ("updated_at", models.DateTimeField(auto_now=True)),
            ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
            ("permission", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="role_permissions", to="access.permission")),
            ("role", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="role_permissions", to="access.role")),
        ], options={"db_table": "access_role_permissions"}),
        migrations.AddField(model_name="role", name="permissions", field=models.ManyToManyField(related_name="roles", through="access.RolePermission", to="access.permission")),
        migrations.AddIndex(model_name="rolepermission", index=models.Index(fields=["role"], name="access_rp_role_idx")),
        migrations.AddConstraint(model_name="rolepermission", constraint=models.UniqueConstraint(fields=("role", "permission"), name="access_role_permission_unique")),
        migrations.AddIndex(model_name="role", index=models.Index(fields=["organization", "slug"], name="access_role_org_slug_idx")),
        migrations.AddConstraint(model_name="role", constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("organization", "slug"), name="access_role_active_slug_unique")),
    ]
