# Generated by Django 5.2.17 on 2026-09-05 13:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name="NexoraUser", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
            ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
            ("email", models.EmailField(blank=True, max_length=254, null=True)), ("display_name", models.CharField(blank=True, max_length=255)),
            ("avatar_url", models.URLField(blank=True, max_length=2048)), ("phone_number", models.CharField(blank=True, max_length=32)),
            ("timezone", models.CharField(default="UTC", max_length=64)), ("locale", models.CharField(default="en-US", max_length=16)),
            ("status", models.CharField(choices=[("active", "Active"), ("suspended", "Suspended"), ("disabled", "Disabled"), ("pending", "Pending"), ("deleted", "Deleted")], db_index=True, default="pending", max_length=16)),
            ("last_login_at", models.DateTimeField(blank=True, null=True)),
        ], options={"db_table": "identity_users", "ordering": ("created_at",)}),
        migrations.CreateModel(name="IdentityProviderAccount", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
            ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)), ("provider", models.CharField(max_length=64)),
            ("provider_subject", models.CharField(max_length=255)), ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ("email_verified", models.BooleanField(default=False)), ("display_name", models.CharField(blank=True, max_length=255)),
            ("claims", models.JSONField(blank=True, default=dict)), ("last_verified_at", models.DateTimeField(blank=True, null=True)),
            ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="provider_accounts", to="identity.nexorauser")),
        ], options={"db_table": "identity_provider_accounts", "indexes": [models.Index(fields=["user", "provider"], name="identity_acct_user_prov_idx")], "constraints": [models.UniqueConstraint(fields=("provider", "provider_subject"), name="identity_provider_subject_unique")]})
    ]
