# Generated by Django 5.2.17 on 2026-09-05 13:56

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("name", models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)])),
                ("slug", models.SlugField(max_length=100)),
                ("status", models.CharField(choices=[("active", "Active"), ("suspended", "Suspended"), ("deactivated", "Deactivated")], db_index=True, default="active", max_length=16)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "organizations",
                "ordering": ("created_at",),
                "indexes": [models.Index(fields=["status"], name="org_status_idx")],
                "constraints": [models.UniqueConstraint(django.db.models.functions.text.Lower("slug"), condition=models.Q(("deleted_at__isnull", True)), name="org_active_slug_unique")],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("status", models.CharField(choices=[("active", "Active"), ("suspended", "Suspended"), ("revoked", "Revoked")], db_index=True, default="active", max_length=16)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="identity.nexorauser")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="organizations.organization")),
            ],
            options={
                "db_table": "organization_memberships",
                "indexes": [models.Index(fields=["organization", "status"], name="membership_org_status_idx"), models.Index(fields=["user", "status"], name="membership_user_status_idx")],
                "constraints": [models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("user", "organization"), name="membership_active_pair_unique")],
            },
        ),
    ]
