# Generated by Django 5.2.17 on 2026-09-06 01:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("products", "0001_initial")]
    operations = [
        migrations.CreateModel(
            name="Capability",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("key", models.CharField(db_index=True, max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message="Capability keys must be lowercase kebab-case identifiers.", regex="^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$")])),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("active", "Active"), ("inactive", "Inactive"), ("deprecated", "Deprecated")], db_index=True, default="active", max_length=16)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={"db_table": "capabilities", "ordering": ("name", "created_at"), "indexes": [models.Index(fields=["status"], name="capability_status_idx")]},
        ),
        migrations.CreateModel(
            name="ProductCapability",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("status", models.CharField(choices=[("active", "Active"), ("inactive", "Inactive")], db_index=True, default="active", max_length=16)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("capability", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="product_capabilities", to="capabilities.capability")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="product_capabilities", to="products.product")),
            ],
            options={"db_table": "product_capabilities", "indexes": [models.Index(fields=["product", "status"], name="prod_cap_product_status_idx"), models.Index(fields=["capability", "status"], name="prod_cap_cap_status_idx")], "constraints": [models.UniqueConstraint(fields=("product", "capability"), name="product_capability_pair_unique")]},
        ),
    ]
